-- Move USER_NOW_PLAYING to GameDB-backed entries (no free text)

ALTER TABLE USER_NOW_PLAYING
  ADD (GAMEDB_GAME_ID NUMBER NULL);

ALTER TABLE USER_NOW_PLAYING
  ADD CONSTRAINT FK_USER_NOW_PLAYING_GAMEDB
  FOREIGN KEY (GAMEDB_GAME_ID)
  REFERENCES GAMEDB_GAMES (GAME_ID);

-- Drop old unique on (USER_ID, TITLE) and replace with (USER_ID, GAMEDB_GAME_ID)
DECLARE
  v_name VARCHAR2(128);
BEGIN
  SELECT constraint_name INTO v_name
  FROM user_constraints
  WHERE table_name = 'USER_NOW_PLAYING'
    AND constraint_type = 'U'
    AND constraint_name LIKE 'UQ_USER_NOW_PLAYING%';

  EXECUTE IMMEDIATE 'ALTER TABLE USER_NOW_PLAYING DROP CONSTRAINT ' || v_name;
EXCEPTION
  WHEN NO_DATA_FOUND THEN NULL;
END;
/

CREATE UNIQUE INDEX UQ_USER_NOW_PLAYING_GAMEDB ON USER_NOW_PLAYING (USER_ID, GAMEDB_GAME_ID);

-- Optional: existing rows without GAMEDB_GAME_ID will be ignored by new code paths.
COMMIT;
