-- Adds GameDB linkage to nomination tables to align with GameDB-only workflow.

ALTER TABLE GOTM_NOMINATIONS
  ADD (GAMEDB_GAME_ID NUMBER NULL);

ALTER TABLE NR_GOTM_NOMINATIONS
  ADD (GAMEDB_GAME_ID NUMBER NULL);

-- Optional: index to support lookups by GameDB id if needed later.
-- CREATE INDEX IX_GOTM_NOMS_GAMEDB ON GOTM_NOMINATIONS (GAMEDB_GAME_ID);
-- CREATE INDEX IX_NR_GOTM_NOMS_GAMEDB ON NR_GOTM_NOMINATIONS (GAMEDB_GAME_ID);

COMMIT;
