-- Track Now Playing forum threads and optionally link them to GameDB games.
-- Forum channel id: 1059875931356938240

CREATE TABLE THREADS (
  THREAD_ID          VARCHAR2(30) PRIMARY KEY, -- Discord thread snowflake
  FORUM_CHANNEL_ID   VARCHAR2(30) NOT NULL,    -- Should be 1059875931356938240
  THREAD_NAME        VARCHAR2(200) NOT NULL,
  GAMEDB_GAME_ID     NUMBER NULL,
  IS_ARCHIVED        CHAR(1) DEFAULT 'N' CHECK (IS_ARCHIVED IN ('Y','N')),
  CREATED_AT         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_SEEN_AT       TIMESTAMP WITH TIME ZONE
);

ALTER TABLE THREADS
  ADD CONSTRAINT FK_THREADS_GAMEDB_GAME
  FOREIGN KEY (GAMEDB_GAME_ID)
  REFERENCES GAMEDB_GAMES (GAME_ID);

CREATE INDEX IX_THREADS_GAMEDB ON THREADS (GAMEDB_GAME_ID);
CREATE INDEX IX_THREADS_FORUM ON THREADS (FORUM_CHANNEL_ID);

COMMIT;
