-- Seeds GOTM nominations for round 133 from prior bot data.
DECLARE
  v_round NUMBER := 133;
BEGIN
  MERGE INTO GOTM_NOMINATIONS t
  USING (SELECT v_round AS ROUND_NUMBER,
               '242859093377810433' AS USER_ID,
               'The Hundred Line: Last Defense Academy' AS GAME_TITLE
          FROM dual) src
     ON (t.ROUND_NUMBER = src.ROUND_NUMBER AND t.USER_ID = src.USER_ID)
   WHEN MATCHED THEN
     UPDATE SET t.GAME_TITLE = src.GAME_TITLE, t.NOMINATED_AT = SYSTIMESTAMP
   WHEN NOT MATCHED THEN
     INSERT (ROUND_NUMBER, USER_ID, GAME_TITLE, NOMINATED_AT)
     VALUES (src.ROUND_NUMBER, src.USER_ID, src.GAME_TITLE, SYSTIMESTAMP);

  MERGE INTO GOTM_NOMINATIONS t
  USING (SELECT v_round AS ROUND_NUMBER,
               '1330369244088504352' AS USER_ID,
               'Octopath Traveler 0' AS GAME_TITLE
          FROM dual) src
     ON (t.ROUND_NUMBER = src.ROUND_NUMBER AND t.USER_ID = src.USER_ID)
   WHEN MATCHED THEN
     UPDATE SET t.GAME_TITLE = src.GAME_TITLE, t.NOMINATED_AT = SYSTIMESTAMP
   WHEN NOT MATCHED THEN
     INSERT (ROUND_NUMBER, USER_ID, GAME_TITLE, NOMINATED_AT)
     VALUES (src.ROUND_NUMBER, src.USER_ID, src.GAME_TITLE, SYSTIMESTAMP);

  MERGE INTO GOTM_NOMINATIONS t
  USING (SELECT v_round AS ROUND_NUMBER,
               '152165643616124928' AS USER_ID,
               'Demeo x Dungeons & Dragons Battlemarked' AS GAME_TITLE
          FROM dual) src
     ON (t.ROUND_NUMBER = src.ROUND_NUMBER AND t.USER_ID = src.USER_ID)
   WHEN MATCHED THEN
     UPDATE SET t.GAME_TITLE = src.GAME_TITLE, t.NOMINATED_AT = SYSTIMESTAMP
   WHEN NOT MATCHED THEN
     INSERT (ROUND_NUMBER, USER_ID, GAME_TITLE, NOMINATED_AT)
     VALUES (src.ROUND_NUMBER, src.USER_ID, src.GAME_TITLE, SYSTIMESTAMP);

  MERGE INTO GOTM_NOMINATIONS t
  USING (SELECT v_round AS ROUND_NUMBER,
               '314394794673569805' AS USER_ID,
               'Disgaea 4: A Promise Unforgotten' AS GAME_TITLE
          FROM dual) src
     ON (t.ROUND_NUMBER = src.ROUND_NUMBER AND t.USER_ID = src.USER_ID)
   WHEN MATCHED THEN
     UPDATE SET t.GAME_TITLE = src.GAME_TITLE, t.NOMINATED_AT = SYSTIMESTAMP
   WHEN NOT MATCHED THEN
     INSERT (ROUND_NUMBER, USER_ID, GAME_TITLE, NOMINATED_AT)
     VALUES (src.ROUND_NUMBER, src.USER_ID, src.GAME_TITLE, SYSTIMESTAMP);

  DBMS_OUTPUT.PUT_LINE('Upserted GOTM nominations for round ' || v_round);
END;
/
COMMIT;
