select * from nr_gotm_entries;

update nr_gotm_entries
set round_number = 130, month_year = 'September 20205', game_index = 1
where round_number = 131;

commit;

-- 1) Drop the current PK on ROUND_NUMBER (adjust name if different)
ALTER TABLE NR_GOTM_ENTRIES DROP PRIMARY KEY;

-- 2) Add the new identity column
ALTER TABLE NR_GOTM_ENTRIES
  ADD (NR_GOTM_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);

-- 3) Make it the primary key
ALTER TABLE NR_GOTM_ENTRIES
  ADD CONSTRAINT PK_NR_GOTM_ENTRIES_ID PRIMARY KEY (NR_GOTM_ID);

-- 4) (Recommended) keep a uniqueness check on round+game_index so game ordering per round stays stable
CREATE UNIQUE INDEX UX_NR_GOTM_ENTRIES_RND_IDX
  ON NR_GOTM_ENTRIES (ROUND_NUMBER, GAME_INDEX);

