ALTER TABLE RPG_CLUB_GAME_KEYS
  ADD (DONOR_NOTIFY_ON_CLAIM NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN RPG_CLUB_GAME_KEYS.DONOR_NOTIFY_ON_CLAIM IS
  '1 when the donor requests a notification on claim.';
