CREATE TABLE GAMEDB_GAME_PLATFORMS (
    GAME_ID NUMBER NOT NULL,
    PLATFORM_ID NUMBER NOT NULL,
    CONSTRAINT PK_GAMEDB_GAME_PLATFORMS PRIMARY KEY (GAME_ID, PLATFORM_ID),
    CONSTRAINT FK_GGP_GAME FOREIGN KEY (GAME_ID) REFERENCES GAMEDB_GAMES(GAME_ID) ON DELETE CASCADE,
    CONSTRAINT FK_GGP_PLATFORM FOREIGN KEY (PLATFORM_ID) REFERENCES GAMEDB_PLATFORMS(PLATFORM_ID)
);

CREATE INDEX IDX_GGP_GAME ON GAMEDB_GAME_PLATFORMS(GAME_ID);
CREATE INDEX IDX_GGP_PLATFORM ON GAMEDB_GAME_PLATFORMS(PLATFORM_ID);
