ALTER TABLE GAMEDB_PLATFORMS ADD PLATFORM_ABBREVIATION VARCHAR2(50);
ALTER TABLE GAMEDB_PLATFORMS ADD PLATFORM_SLUG VARCHAR2(255);
ALTER TABLE GAMEDB_PLATFORMS ADD PLATFORM_CHECKSUM VARCHAR2(64);
ALTER TABLE GAMEDB_PLATFORMS ADD IGDB_UPDATED_AT NUMBER;
