ALTER TABLE RPG_CLUB_TODOS
ADD CATEGORY VARCHAR2(20) DEFAULT 'Improvements' NOT NULL;

UPDATE RPG_CLUB_TODOS
SET CATEGORY = 'Improvements'
WHERE CATEGORY IS NULL;

ALTER TABLE RPG_CLUB_TODOS
ADD CONSTRAINT CK_RPG_CLUB_TODOS_CATEGORY
CHECK (CATEGORY IN ('New Features', 'Improvements', 'Defects'));
