ALTER TABLE RPG_CLUB_TODOS
ADD (
  TODO_CATEGORY VARCHAR2(20) DEFAULT 'Improvements' NOT NULL,
  CONSTRAINT CK_RPG_CLUB_TODOS_TODO_CATEGORY
    CHECK (TODO_CATEGORY IN ('New Features', 'Improvements', 'Defects'))
);
