CREATE TABLE RPG_CLUB_PRESENCE_PROMPT_OPTS (
  USER_ID VARCHAR2(30) NOT NULL,
  SCOPE VARCHAR2(10) NOT NULL,
  GAME_TITLE VARCHAR2(300),
  GAME_TITLE_NORM VARCHAR2(300) NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RPG_CLUB_PRESENCE_PROMPT_OPTS PRIMARY KEY (USER_ID, SCOPE, GAME_TITLE_NORM),
  CONSTRAINT CK_RPG_CLUB_PRESENCE_PROMPT_SCOPE CHECK (SCOPE IN ('ALL', 'GAME'))
);
