ALTER TABLE RPG_CLUB_TODOS
ADD TODO_CATEGORY VARCHAR2(20) DEFAULT 'Improvements' NOT NULL;

UPDATE RPG_CLUB_TODOS
SET TODO_CATEGORY = 'Improvements'
WHERE TODO_CATEGORY IS NULL;

ALTER TABLE RPG_CLUB_TODOS
ADD CONSTRAINT CK_RPG_CLUB_TODOS_TODO_CATEGORY
CHECK (TODO_CATEGORY IN ('New Features', 'Improvements', 'Defects'));
