ALTER TABLE RPG_CLUB_USERS
  ADD (DONOR_NOTIFY_ON_CLAIM NUMBER(1) DEFAULT 0 NOT NULL);

COMMENT ON COLUMN RPG_CLUB_USERS.DONOR_NOTIFY_ON_CLAIM IS
  '1 when the user wants to be notified when a donated key is claimed.';

ALTER TABLE RPG_CLUB_USERS_HIST
  ADD (DONOR_NOTIFY_ON_CLAIM NUMBER(1));

COMMENT ON COLUMN RPG_CLUB_USERS_HIST.DONOR_NOTIFY_ON_CLAIM IS
  'Audit snapshot of donor notification preference.';
