export const GAMEDB_CSV_PLATFORM_MAP: Record<string, string[]> = {
  "pc / windows": ["PC (Microsoft Windows)"],
  "pc": ["PC (Microsoft Windows)"],
  "windows": ["PC (Microsoft Windows)"],
  "mac": ["Mac"],
  "mac os": ["Mac"],
  "linux": ["Linux"],
  "steam deck": ["Steam Deck"],
  "playstation": ["PlayStation"],
  "ps1": ["PlayStation"],
  "playstation 2": ["PlayStation 2"],
  "ps2": ["PlayStation 2"],
  "playstation 3": ["PlayStation 3"],
  "ps3": ["PlayStation 3"],
  "playstation 4": ["PlayStation 4"],
  "ps4": ["PlayStation 4"],
  "playstation 5": ["PlayStation 5"],
  "ps5": ["PlayStation 5"],
  "playstation portable": ["PSP"],
  "psp": ["PSP"],
  "ps vita": ["PlayStation Vita"],
  "vita": ["PlayStation Vita"],
  "xbox": ["Xbox"],
  "xbox 360": ["Xbox 360"],
  "xbox one": ["Xbox One"],
  "xbox series x|s": ["Xbox Series X|S"],
  "xbox series": ["Xbox Series X|S"],
  "nintendo switch": ["Switch"],
  "switch": ["Switch"],
  "wii": ["Wii"],
  "wii u": ["Wii U"],
  "gamecube": ["GameCube"],
  "nintendo 64": ["Nintendo 64"],
  "n64": ["Nintendo 64"],
  "nintendo ds": ["Nintendo DS"],
  "nds": ["Nintendo DS"],
  "nintendo 3ds": ["Nintendo 3DS"],
  "3ds": ["Nintendo 3DS"],
  "game boy": ["Game Boy"],
  "game boy color": ["Game Boy Color"],
  "gbc": ["Game Boy Color"],
  "game boy advance": ["Game Boy Advance"],
  "gba": ["Game Boy Advance"],
  "ios": ["iOS"],
  "iphone": ["iOS"],
  "ipad": ["iOS"],
  "android": ["Android"],
  "browser": ["Browser"],
  "web": ["Browser"],
  "arcade": ["Arcade"],
};
