export const GAMEDB_CSV_PLATFORM_MAP: Record<string, string[]> = {
  "android": ["Android"],
  "apple ii": ["Apple II"],
  "arcade": ["Arcade"],
  "atari 2600": ["Atari 2600"],
  "atari 8 bit computer": ["Atari 8-bit"],
  "atari st": ["Atari ST/STE"],
  "browser": ["Browser"],
  "dreamcast": ["Dreamcast"],
  "game boy": ["Game Boy"],
  "game boy advance": ["Game Boy Advance"],
  "game boy color": ["Game Boy Color"],
  "game gear": ["Sega Game Gear"],
  "gamecube": ["Nintendo GameCube"],
  "gba": ["Game Boy Advance"],
  "gbc": ["Game Boy Color"],
  "genesis": ["Sega Genesis"],
  "ios": ["iOS"],
  "ipad": ["iOS"],
  "iphone": ["iOS"],
  "linux": ["Linux"],
  "mac": ["Mac"],
  "mac os": ["Mac"],
  "mobile (android)": ["Android"],
  "mobile (ios)": ["iOS"],
  "mobile android": ["Android"],
  "mobile ios": ["iOS"],
  "n64": ["Nintendo 64"],
  "nds": ["Nintendo DS"],
  "nintendo 3ds": ["Nintendo 3DS"],
  "nintendo 64": ["Nintendo 64"],
  "nintendo ds": ["Nintendo DS"],
  "nintendo entertainment system": ["Nintendo Entertainment System"],
  "nintendo switch": ["Switch"],
  "nintendo switch 2": ["Switch 2"],
  "pc": ["Windows"],
  "pc / windows": ["Windows"],
  "playstation": ["PlayStation"],
  "playstation 2": ["PlayStation 2"],
  "playstation 3": ["PlayStation 3"],
  "playstation 4": ["PlayStation 4"],
  "playstation 5": ["PlayStation 5"],
  "playstation portable": ["PlayStation Portable"],
  "playstation vita": ["PlayStation Vita"],
  "ps1": ["PlayStation"],
  "ps2": ["PlayStation 2"],
  "ps3": ["PlayStation 3"],
  "ps4": ["PlayStation 4"],
  "ps5": ["PlayStation 5"],
  "ps vita": ["PlayStation Vita"],
  "psp": ["PSP"],
  "saturn": ["Sega Saturn"],
  "sega master system": ["Master System"],
  "steam deck": ["Steam Deck"],
  "super nintendo entertainment system": ["Super Nintendo Entertainment System"],
  "switch": ["Switch"],
  "vita": ["PlayStation Vita"],
  "web": ["Browser"],
  "wii": ["Wii"],
  "wii u": ["WiiU"],
  "windows": ["Windows"],
  "xbox": ["Xbox"],
  "xbox 360": ["Xbox 360"],
  "xbox one": ["Xbox One"],
  "xbox series": ["Xbox Series X|S"],
  "xbox series x|s": ["Xbox Series X|S"],
  "zx spectrum": ["ZX Spectrum"]
};
