CREATE TABLE USER_GAME_COLLECTIONS (
  ENTRY_ID        NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID         VARCHAR2(50) NOT NULL,
  GAMEDB_GAME_ID  NUMBER(10) NOT NULL,
  PLATFORM_ID     NUMBER,
  OWNERSHIP_TYPE  VARCHAR2(30) DEFAULT 'Digital' NOT NULL,
  NOTE            VARCHAR2(500),
  IS_SHARED       NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_GAME_COLLECTIONS
  ADD CONSTRAINT FK_UGCOL_GAMEDB_GAME
  FOREIGN KEY (GAMEDB_GAME_ID)
  REFERENCES GAMEDB_GAMES (GAME_ID);

ALTER TABLE USER_GAME_COLLECTIONS
  ADD CONSTRAINT FK_UGCOL_PLATFORM
  FOREIGN KEY (PLATFORM_ID)
  REFERENCES GAMEDB_PLATFORMS (PLATFORM_ID);

ALTER TABLE USER_GAME_COLLECTIONS
  ADD CONSTRAINT CK_UGCOL_OWNERSHIP_TYPE
  CHECK (OWNERSHIP_TYPE IN ('Digital', 'Physical', 'Subscription', 'Other'));

ALTER TABLE USER_GAME_COLLECTIONS
  ADD CONSTRAINT CK_UGCOL_SHARED
  CHECK (IS_SHARED IN (0, 1));

CREATE UNIQUE INDEX UQ_USER_GAME_COLLECTIONS_DEDUP
  ON USER_GAME_COLLECTIONS (
    USER_ID,
    GAMEDB_GAME_ID,
    NVL(PLATFORM_ID, -1),
    OWNERSHIP_TYPE
  );

CREATE INDEX IX_UGCOL_USER ON USER_GAME_COLLECTIONS (USER_ID);
CREATE INDEX IX_UGCOL_GAME ON USER_GAME_COLLECTIONS (GAMEDB_GAME_ID);
CREATE INDEX IX_UGCOL_PLATFORM ON USER_GAME_COLLECTIONS (PLATFORM_ID);
CREATE INDEX IX_UGCOL_SHARED ON USER_GAME_COLLECTIONS (USER_ID, IS_SHARED);

CREATE OR REPLACE TRIGGER TRG_USER_GAME_COLLECTIONS_UPD
BEFORE UPDATE ON USER_GAME_COLLECTIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

COMMIT;
