DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'USER_NOW_PLAYING'
     AND COLUMN_NAME = 'PLATFORM_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USER_NOW_PLAYING ADD PLATFORM_ID NUMBER';
  END IF;
END;
/

DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_USER_NOW_PLAYING_PLATFORM'
     AND TABLE_NAME = 'USER_NOW_PLAYING';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE USER_NOW_PLAYING
      ADD CONSTRAINT FK_USER_NOW_PLAYING_PLATFORM
      FOREIGN KEY (PLATFORM_ID)
      REFERENCES GAMEDB_PLATFORMS (PLATFORM_ID)';
  END IF;
END;
/

DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IX_USER_NOW_PLAYING_PLATFORM';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE INDEX IX_USER_NOW_PLAYING_PLATFORM
      ON USER_NOW_PLAYING (PLATFORM_ID)';
  END IF;
END;
/
