CREATE TABLE RPG_CLUB_PRESENCE_PROMPT_HISTORY (
  PROMPT_ID VARCHAR2(64) NOT NULL,
  USER_ID VARCHAR2(30) NOT NULL,
  GAME_TITLE VARCHAR2(300) NOT NULL,
  GAME_TITLE_NORM VARCHAR2(300) NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  RESOLVED_AT TIMESTAMP(6) WITH TIME ZONE,
  CONSTRAINT PK_RPG_CLUB_PRESENCE_PROMPT_HISTORY PRIMARY KEY (PROMPT_ID)
);

CREATE INDEX IDX_RPG_CLUB_PRESENCE_PROMPT_HIST_USER
  ON RPG_CLUB_PRESENCE_PROMPT_HISTORY (USER_ID, GAME_TITLE_NORM, STATUS);
