CREATE TABLE RPG_CLUB_STARBOARD (
  MESSAGE_ID VARCHAR2(30) NOT NULL,
  CHANNEL_ID VARCHAR2(30) NOT NULL,
  STARBOARD_MESSAGE_ID VARCHAR2(30) NOT NULL,
  AUTHOR_ID VARCHAR2(30) NOT NULL,
  STAR_COUNT NUMBER(5,0) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RPG_CLUB_STARBOARD PRIMARY KEY (MESSAGE_ID)
);
