BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RPG_CLUB_TODOS DROP CONSTRAINT CK_RPG_CLUB_TODOS_TODO_CATEGORY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE RPG_CLUB_TODOS DROP CONSTRAINT CK_RPG_CLUB_TODOS_CATEGORY';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 THEN RAISE; END IF;
END;
/

ALTER TABLE RPG_CLUB_TODOS
  ADD CONSTRAINT CK_RPG_CLUB_TODOS_TODO_CATEGORY
  CHECK (TODO_CATEGORY IN ('New Features', 'Improvements', 'Defects', 'Blocked', 'Refactoring'));
