ALTER TABLE USER_GAME_COMPLETIONS ADD PLATFORM_ID NUMBER;

ALTER TABLE USER_GAME_COMPLETIONS
  ADD CONSTRAINT FK_USER_GAME_COMPLETIONS_PLATFORM
  FOREIGN KEY (PLATFORM_ID)
  REFERENCES GAMEDB_PLATFORMS (PLATFORM_ID);

CREATE INDEX IDX_USER_GAME_COMPLETIONS_PLATFORM ON USER_GAME_COMPLETIONS (PLATFORM_ID);
