ALTER TABLE GAMEDB_GAMES ADD INITIAL_RELEASE_DATE DATE;

UPDATE GAMEDB_GAMES g
SET INITIAL_RELEASE_DATE = (
  SELECT MIN(r.RELEASE_DATE)
  FROM GAMEDB_RELEASES r
  WHERE r.GAME_ID = g.GAME_ID
    AND r.RELEASE_DATE IS NOT NULL
)
WHERE EXISTS (
  SELECT 1
  FROM GAMEDB_RELEASES r
  WHERE r.GAME_ID = g.GAME_ID
    AND r.RELEASE_DATE IS NOT NULL
);
