DECLARE
  v_constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_constraint_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'UK_GAMEDB_SEARCH_SYNONYMS_NORM'
     AND TABLE_NAME = 'GAMEDB_SEARCH_SYNONYMS';
  IF v_constraint_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE GAMEDB_SEARCH_SYNONYMS DROP CONSTRAINT UK_GAMEDB_SEARCH_SYNONYMS_NORM';
  END IF;

  SELECT COUNT(*)
    INTO v_constraint_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'UK_GAMEDB_SEARCH_SYNONYMS_GROUP_NORM'
     AND TABLE_NAME = 'GAMEDB_SEARCH_SYNONYMS';
  IF v_constraint_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE GAMEDB_SEARCH_SYNONYMS
      ADD CONSTRAINT UK_GAMEDB_SEARCH_SYNONYMS_GROUP_NORM UNIQUE (GROUP_ID, TERM_NORM)';
  END IF;
END;
/
