CREATE TABLE RPG_CLUB_SUGGESTION_REVIEW_SESSIONS (
  SESSION_ID      VARCHAR2(120) PRIMARY KEY,
  REVIEWER_ID     VARCHAR2(30) NOT NULL,
  SUGGESTION_IDS  VARCHAR2(4000) NOT NULL,
  CURRENT_INDEX   NUMBER DEFAULT 0 NOT NULL,
  TOTAL_COUNT     NUMBER DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_RPG_CLUB_SUG_REV_SESS_REVIEWER
  ON RPG_CLUB_SUGGESTION_REVIEW_SESSIONS (REVIEWER_ID);

CREATE INDEX IX_RPG_CLUB_SUG_REV_SESS_CREATED
  ON RPG_CLUB_SUGGESTION_REVIEW_SESSIONS (CREATED_AT);

CREATE OR REPLACE TRIGGER TRG_RPG_CLUB_SUG_REV_SESS_UPD
BEFORE UPDATE ON RPG_CLUB_SUGGESTION_REVIEW_SESSIONS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

commit;
