CREATE TABLE GAMEDB_GAME_ALTERNATES (
  GAME_ID NUMBER NOT NULL,
  ALT_GAME_ID NUMBER NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(64),
  CONSTRAINT PK_GAMEDB_GAME_ALTERNATES PRIMARY KEY (GAME_ID, ALT_GAME_ID),
  CONSTRAINT CK_GAMEDB_GAME_ALTS_ORDER CHECK (GAME_ID < ALT_GAME_ID),
  CONSTRAINT FK_GAMEDB_GAME_ALTS_GAME FOREIGN KEY (GAME_ID)
    REFERENCES GAMEDB_GAMES (GAME_ID),
  CONSTRAINT FK_GAMEDB_GAME_ALTS_ALT FOREIGN KEY (ALT_GAME_ID)
    REFERENCES GAMEDB_GAMES (GAME_ID)
);
