CREATE TABLE GAMEDB_RELEASE_ANNOUNCEMENTS (
  RELEASE_ID NUMBER NOT NULL,
  ANNOUNCE_AT DATE NOT NULL,
  SENT_AT TIMESTAMP NULL,
  SKIPPED_AT TIMESTAMP NULL,
  SKIP_REASON VARCHAR2(80) NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_GAMEDB_RELEASE_ANNOUNCEMENTS PRIMARY KEY (RELEASE_ID),
  CONSTRAINT FK_GAMEDB_RELEASE_ANNOUNCEMENTS_RELEASE
    FOREIGN KEY (RELEASE_ID) REFERENCES GAMEDB_RELEASES(RELEASE_ID)
);

CREATE INDEX IDX_GAMEDB_RELEASE_ANNOUNCE_PENDING
  ON GAMEDB_RELEASE_ANNOUNCEMENTS (SENT_AT, SKIPPED_AT, ANNOUNCE_AT);

CREATE OR REPLACE TRIGGER TRG_GAMEDB_RELEASE_ANNOUNCEMENTS_UPD
BEFORE UPDATE ON GAMEDB_RELEASE_ANNOUNCEMENTS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

INSERT INTO GAMEDB_RELEASE_ANNOUNCEMENTS (
  RELEASE_ID,
  ANNOUNCE_AT,
  SENT_AT,
  SKIPPED_AT,
  SKIP_REASON
)
SELECT
  r.RELEASE_ID,
  r.RELEASE_DATE - 7,
  NULL,
  NULL,
  NULL
FROM GAMEDB_RELEASES r
WHERE r.RELEASE_DATE IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM GAMEDB_RELEASE_ANNOUNCEMENTS a
    WHERE a.RELEASE_ID = r.RELEASE_ID
  );

COMMIT;
