-- Track user game completions (replays allowed).
CREATE TABLE USER_GAME_COMPLETIONS (
  COMPLETION_ID      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID            VARCHAR2(50) NOT NULL,
  GAMEDB_GAME_ID     NUMBER(10)   NOT NULL,
  COMPLETION_TYPE    VARCHAR2(50) NOT NULL,
  COMPLETED_AT       DATE         DEFAULT TRUNC(SYSDATE),
  FINAL_PLAYTIME_HRS NUMBER(8,2),
  CREATED_AT         TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE USER_GAME_COMPLETIONS
  ADD CONSTRAINT CK_USER_GAME_COMPLETIONS_TYPE
  CHECK (COMPLETION_TYPE IN ('Main Story', 'Main Story + Side Content', 'Completionist'));

ALTER TABLE USER_GAME_COMPLETIONS
  ADD CONSTRAINT FK_UGC_GAMEDB_GAME
  FOREIGN KEY (GAMEDB_GAME_ID)
  REFERENCES GAMEDB_GAMES (GAME_ID);

CREATE INDEX IX_UGC_USER ON USER_GAME_COMPLETIONS (USER_ID);
CREATE INDEX IX_UGC_GAME ON USER_GAME_COMPLETIONS (GAMEDB_GAME_ID);
