CREATE TABLE RPG_CLUB_USER_CHANNEL_COUNTS (
  USER_ID         VARCHAR2(30) NOT NULL,
  CHANNEL_ID      VARCHAR2(30) NOT NULL,
  MESSAGE_COUNT   NUMBER(12,0) DEFAULT 0 NOT NULL,
  LAST_SCANNED_AT TIMESTAMP WITH TIME ZONE,
  CREATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RPG_CLUB_USER_CHANNEL_COUNTS PRIMARY KEY (USER_ID, CHANNEL_ID)
);

CREATE OR REPLACE TRIGGER TRG_RPG_CLUB_USER_CHANNEL_COUNTS_UPD
BEFORE UPDATE ON RPG_CLUB_USER_CHANNEL_COUNTS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

commit;
