-- Support multiple GameDB links per thread.
CREATE TABLE THREAD_GAME_LINKS (
  THREAD_ID      VARCHAR2(50) NOT NULL,
  GAMEDB_GAME_ID NUMBER(10)   NOT NULL,
  LINKED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_THREAD_GAME_LINKS PRIMARY KEY (THREAD_ID, GAMEDB_GAME_ID)
);

CREATE INDEX IX_THREAD_GAME_LINKS_GAME ON THREAD_GAME_LINKS (GAMEDB_GAME_ID);

COMMENT ON TABLE THREAD_GAME_LINKS IS 'Associates threads to one or more GameDB games.';
COMMENT ON COLUMN THREAD_GAME_LINKS.THREAD_ID IS 'Discord thread id';
COMMENT ON COLUMN THREAD_GAME_LINKS.GAMEDB_GAME_ID IS 'GameDB game id';
COMMENT ON COLUMN THREAD_GAME_LINKS.LINKED_AT IS 'When this link was created';

-- Backfill from existing single-link column.
MERGE INTO THREAD_GAME_LINKS tgt
USING (
  SELECT THREAD_ID, GAMEDB_GAME_ID
  FROM THREADS
  WHERE GAMEDB_GAME_ID IS NOT NULL
) src
ON (tgt.THREAD_ID = src.THREAD_ID AND tgt.GAMEDB_GAME_ID = src.GAMEDB_GAME_ID)
WHEN NOT MATCHED THEN
  INSERT (THREAD_ID, GAMEDB_GAME_ID, LINKED_AT)
  VALUES (src.THREAD_ID, src.GAMEDB_GAME_ID, SYSTIMESTAMP);
