CREATE TABLE RPG_CLUB_USERS (
  USER_ID           VARCHAR2(30) PRIMARY KEY,   -- Discord snowflake
  IS_BOT            NUMBER(1,0) DEFAULT 0 NOT NULL, -- 0/1 flag
  USERNAME          VARCHAR2(100),
  GLOBAL_NAME       VARCHAR2(100),
  AVATAR_BLOB       BLOB,                        -- raw avatar image blob
  SERVER_JOINED_AT  TIMESTAMP WITH TIME ZONE,    -- when joined the guild
  LAST_SEEN_AT      TIMESTAMP WITH TIME ZONE,    -- last activity we observed
  LAST_FETCHED_AT   TIMESTAMP WITH TIME ZONE,    -- when we last pulled user data

  ROLE_ADMIN        NUMBER(1,0) DEFAULT 0 NOT NULL,
  ROLE_MODERATOR    NUMBER(1,0) DEFAULT 0 NOT NULL,
  ROLE_REGULAR      NUMBER(1,0) DEFAULT 0 NOT NULL,
  ROLE_MEMBER       NUMBER(1,0) DEFAULT 0 NOT NULL,
  ROLE_NEWCOMER     NUMBER(1,0) DEFAULT 0 NOT NULL,

  CREATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- Keep UPDATED_AT fresh on updates
CREATE OR REPLACE TRIGGER TRG_RPG_CLUB_USERS_UPD
BEFORE UPDATE ON RPG_CLUB_USERS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- Optional: view to show “member duration” as years/months/days since join
CREATE OR REPLACE VIEW RPG_CLUB_USERS_MEMBERSHIP_V AS
SELECT
  USER_ID,
  IS_BOT,
  USERNAME,
  GLOBAL_NAME,
  SERVER_JOINED_AT,
  LAST_SEEN_AT,
  LAST_FETCHED_AT,
  ROLE_ADMIN,
  ROLE_MODERATOR,
  ROLE_REGULAR,
  ROLE_MEMBER,
  ROLE_NEWCOMER,
  FLOOR(MONTHS_BETWEEN(SYSTIMESTAMP, SERVER_JOINED_AT) / 12) AS YEARS,
  MOD(FLOOR(MONTHS_BETWEEN(SYSTIMESTAMP, SERVER_JOINED_AT)), 12) AS MONTHS,
  FLOOR(
    SYSTIMESTAMP
    - ADD_MONTHS(SERVER_JOINED_AT, FLOOR(MONTHS_BETWEEN(SYSTIMESTAMP, SERVER_JOINED_AT)))
  ) AS DAYS
FROM RPG_CLUB_USERS;

commit;
