-- Drops legacy GAME_TITLE columns now that nominations rely on GameDB metadata.
-- Ensure GAMEDB_GAME_ID is populated for all rows before running the NOT NULL change.

DECLARE
  v_count NUMBER := 0;
  v_nullable VARCHAR2(1);
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'GOTM_NOMINATIONS'
    AND COLUMN_NAME = 'GAMEDB_GAME_ID';
  IF v_count > 0 THEN
    SELECT NULLABLE INTO v_nullable
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'GOTM_NOMINATIONS'
      AND COLUMN_NAME = 'GAMEDB_GAME_ID';
    IF v_nullable = 'Y' THEN
      SELECT COUNT(*)
        INTO v_count
        FROM GOTM_NOMINATIONS
       WHERE GAMEDB_GAME_ID IS NULL;
      IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE GOTM_NOMINATIONS MODIFY (GAMEDB_GAME_ID NOT NULL)';
      END IF;
    END IF;
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'GOTM_NOMINATIONS'
    AND COLUMN_NAME = 'GAME_TITLE';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE GOTM_NOMINATIONS DROP COLUMN GAME_TITLE';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'NR_GOTM_NOMINATIONS'
    AND COLUMN_NAME = 'GAMEDB_GAME_ID';
  IF v_count > 0 THEN
    SELECT NULLABLE INTO v_nullable
    FROM USER_TAB_COLS
    WHERE TABLE_NAME = 'NR_GOTM_NOMINATIONS'
      AND COLUMN_NAME = 'GAMEDB_GAME_ID';
    IF v_nullable = 'Y' THEN
      SELECT COUNT(*)
        INTO v_count
        FROM NR_GOTM_NOMINATIONS
       WHERE GAMEDB_GAME_ID IS NULL;
      IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NR_GOTM_NOMINATIONS MODIFY (GAMEDB_GAME_ID NOT NULL)';
      END IF;
    END IF;
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'NR_GOTM_NOMINATIONS'
    AND COLUMN_NAME = 'GAME_TITLE';
  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE NR_GOTM_NOMINATIONS DROP COLUMN GAME_TITLE';
  END IF;
END;
/

COMMIT;
