-- Rewrite TRG_RPG_CLUB_USERS_AUD to avoid storing avatars in the history table

CREATE OR REPLACE TRIGGER TRG_RPG_CLUB_USERS_AUD
AFTER INSERT OR UPDATE OR DELETE ON RPG_CLUB_USERS
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO RPG_CLUB_USERS_HIST (
      USER_ID, IS_BOT, USERNAME, GLOBAL_NAME,
      SERVER_JOINED_AT, SERVER_LEFT_AT, LAST_SEEN_AT, LAST_FETCHED_AT,
      ROLE_ADMIN, ROLE_MODERATOR, ROLE_REGULAR, ROLE_MEMBER, ROLE_NEWCOMER,
      MESSAGE_COUNT, COMPLETIONATOR_URL, PSN_USERNAME, XBL_USERNAME, NSW_FRIEND_CODE,
      STEAM_URL, PROFILE_IMAGE_AT, CREATED_AT, UPDATED_AT,
      ACTION_TYPE
    ) VALUES (
      :NEW.USER_ID, :NEW.IS_BOT, :NEW.USERNAME, :NEW.GLOBAL_NAME,
      :NEW.SERVER_JOINED_AT, :NEW.SERVER_LEFT_AT, :NEW.LAST_SEEN_AT, :NEW.LAST_FETCHED_AT,
      :NEW.ROLE_ADMIN, :NEW.ROLE_MODERATOR, :NEW.ROLE_REGULAR, :NEW.ROLE_MEMBER, :NEW.ROLE_NEWCOMER,
      :NEW.MESSAGE_COUNT, :NEW.COMPLETIONATOR_URL, :NEW.PSN_USERNAME, :NEW.XBL_USERNAME, :NEW.NSW_FRIEND_CODE,
      :NEW.STEAM_URL, :NEW.PROFILE_IMAGE_AT, :NEW.CREATED_AT, :NEW.UPDATED_AT,
      'I'
    );
  ELSIF UPDATING THEN
    INSERT INTO RPG_CLUB_USERS_HIST (
      USER_ID, IS_BOT, USERNAME, GLOBAL_NAME,
      SERVER_JOINED_AT, SERVER_LEFT_AT, LAST_SEEN_AT, LAST_FETCHED_AT,
      ROLE_ADMIN, ROLE_MODERATOR, ROLE_REGULAR, ROLE_MEMBER, ROLE_NEWCOMER,
      MESSAGE_COUNT, COMPLETIONATOR_URL, PSN_USERNAME, XBL_USERNAME, NSW_FRIEND_CODE,
      STEAM_URL, PROFILE_IMAGE_AT, CREATED_AT, UPDATED_AT,
      ACTION_TYPE
    ) VALUES (
      :OLD.USER_ID, :OLD.IS_BOT, :OLD.USERNAME, :OLD.GLOBAL_NAME,
      :OLD.SERVER_JOINED_AT, :OLD.SERVER_LEFT_AT, :OLD.LAST_SEEN_AT, :OLD.LAST_FETCHED_AT,
      :OLD.ROLE_ADMIN, :OLD.ROLE_MODERATOR, :OLD.ROLE_REGULAR, :OLD.ROLE_MEMBER, :OLD.ROLE_NEWCOMER,
      :OLD.MESSAGE_COUNT, :OLD.COMPLETIONATOR_URL, :OLD.PSN_USERNAME, :OLD.XBL_USERNAME, :OLD.NSW_FRIEND_CODE,
      :OLD.STEAM_URL, :OLD.PROFILE_IMAGE_AT, :OLD.CREATED_AT, :OLD.UPDATED_AT,
      'U'
    );
  ELSIF DELETING THEN
    INSERT INTO RPG_CLUB_USERS_HIST (
      USER_ID, IS_BOT, USERNAME, GLOBAL_NAME,
      SERVER_JOINED_AT, SERVER_LEFT_AT, LAST_SEEN_AT, LAST_FETCHED_AT,
      ROLE_ADMIN, ROLE_MODERATOR, ROLE_REGULAR, ROLE_MEMBER, ROLE_NEWCOMER,
      MESSAGE_COUNT, COMPLETIONATOR_URL, PSN_USERNAME, XBL_USERNAME, NSW_FRIEND_CODE,
      STEAM_URL, PROFILE_IMAGE_AT, CREATED_AT, UPDATED_AT,
      ACTION_TYPE
    ) VALUES (
      :OLD.USER_ID, :OLD.IS_BOT, :OLD.USERNAME, :OLD.GLOBAL_NAME,
      :OLD.SERVER_JOINED_AT, :OLD.SERVER_LEFT_AT, :OLD.LAST_SEEN_AT, :OLD.LAST_FETCHED_AT,
      :OLD.ROLE_ADMIN, :OLD.ROLE_MODERATOR, :OLD.ROLE_REGULAR, :OLD.ROLE_MEMBER, :OLD.ROLE_NEWCOMER,
      :OLD.MESSAGE_COUNT, :OLD.COMPLETIONATOR_URL, :OLD.PSN_USERNAME, :OLD.XBL_USERNAME, :OLD.NSW_FRIEND_CODE,
      :OLD.STEAM_URL, :OLD.PROFILE_IMAGE_AT, :OLD.CREATED_AT, :OLD.UPDATED_AT,
      'D'
    );
  END IF;
END;
/

commit;
