CREATE TABLE USER_REMINDERS (
  REMINDER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID VARCHAR2(32) NOT NULL,
  REMIND_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CONTENT VARCHAR2(400) NOT NULL,
  SENT_AT TIMESTAMP WITH TIME ZONE NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX UX_USER_REMINDERS_USER ON USER_REMINDERS (USER_ID, REMIND_AT);
CREATE INDEX UX_USER_REMINDERS_DUE ON USER_REMINDERS (SENT_AT, REMIND_AT);
