-- Expand RPG_CLUB_USERS with profile/social fields
ALTER TABLE RPG_CLUB_USERS ADD (
  COMPLETIONATOR_URL   VARCHAR2(512),
  PSN_USERNAME         VARCHAR2(100),
  XBL_USERNAME         VARCHAR2(100),
  NSW_FRIEND_CODE      VARCHAR2(50),
  STEAM_URL            VARCHAR2(512)
);
